/**
 * alert-resolver.ts
 *
 * WHY: Converts a live AlertData + EvidencePayload into a safe TriageGraph
 * that the <TriageGraphCard> can render without ever surfacing raw payload
 * content, snippet data, or credentials in the UI layer.
 *
 * The function is intentionally pure — no I/O, no fetches, no side effects.
 * Every value in the output is derived from operator-summary-grade fields only.
 * Raw-payload access happens in dedicated RBAC-gated panels (Audit & Evidence,
 * Traffic Monitor) — not here.
 *
 * Resolver version: alert-resolver-v1
 */

import type { TabId } from "../types";
import type { AlertData, EvidencePayload } from "../types";
import type {
  TriageGraph,
  TriageStage,
  TriageArtifact,
  TriageStageId,
  TriageIssueSummary,
} from "./types";
import { TRIAGE_STAGE_ORDER } from "./types";
import { makeLastHoursFilter } from "./navigation";

// ---------------------------------------------------------------------------
// Public input contract
// ---------------------------------------------------------------------------

export interface ResolveAlertTriageInput {
  alert: AlertData;
  /**
   * Evidence payload returned by GET /api/alerts/:id/evidence.
   * Optional — alerts can exist before an evidence row is correlated.
   */
  evidence?: EvidencePayload | null;
  /**
   * "Now" reference for time-window filters. Defaults to new Date() so callers
   * do not need to pass it; tests can inject a fixed value for determinism.
   */
  now?: Date;
  /**
   * Caller's permission set. Reserved for future permission-gated artifacts
   * (e.g. "policies:write"). Not enforced in v1 — included for interface
   * stability so callers don't need a breaking change later.
   */
  permissions?: Set<string>;
}

// ---------------------------------------------------------------------------
// Resolver version stamp — bumped when output shape changes materially
// ---------------------------------------------------------------------------

const RESOLVER_VERSION = "alert-resolver-v1";

// ---------------------------------------------------------------------------
// Source-aware missing-state copy
//
// operator flagged 2026-05-07 looking at a session-watcher alert: the generic
// "No audit event correlated to this alert yet" copy hides the actual
// reason. session-watcher reads existing log files on disk; if the source
// session wasn't routed through the LiteLLM proxy at capture time, no
// audit row will EVER be correlated — that's accurate, not pending. Other
// sources have their own per-source semantics. These helpers return copy
// that tells the operator *why* a given stage is missing without leaking
// implementation detail.
// ---------------------------------------------------------------------------

function missingEvidenceReason(alert: AlertData): string {
  switch (alert.source) {
    case "session-watcher":
      return "This alert was generated by session-log scanning. No LiteLLM audit event is correlated because this session wasn't routed through the proxy at capture time.";
    case "shield":
      return "No audit row has been correlated yet — Shield can fire before the audit log writes for the same request.";
    case "correlation-engine":
      return "Correlation engine generated this from prior signals; no specific audit event is tied to it directly.";
    default:
      return "No audit event has been correlated to this alert yet.";
  }
}

function missingSourceEventReason(alert: AlertData): string {
  switch (alert.source) {
    case "session-watcher":
      return "Session-watcher reads from disk-stored OpenClaw session logs. The upstream LiteLLM proxy did not record this session, so no proxy traffic row exists.";
    case "shield":
      return "Proxy traffic row not yet correlated to this Shield event.";
    case "correlation-engine":
      return "Correlations fire across multiple events; there is no single proxy traffic row to link.";
    default:
      return "No proxy traffic row is linked to this alert yet.";
  }
}

function missingAffectedObjectReason(alert: AlertData): string {
  switch (alert.source) {
    case "session-watcher":
      return "This alert is bound to a session log file but no in-DB session_id has been resolved yet. Inspect the original log via Audit & Evidence.";
    case "correlation-engine":
      return "Correlation alerts span multiple sessions; no single affected object exists.";
    default:
      return "No session or object identifier is linked to this alert yet.";
  }
}

// ---------------------------------------------------------------------------
// session_id fallback — pull from alert.metadata JSON or description text
//
// operator flagged 2026-05-07: the resolver only read evidence.session_id, so
// the Affected Object stage stayed missing for any alert where evidence
// hadn't been fetched (or never will be — see missingEvidenceReason above).
// session-watcher writes the session UUID into alert.description as
// "Session: <uuid>"; some sources may also stuff it in alert.metadata as
// JSON. Try both before giving up.
//
// UUID regex matches the canonical 8-4-4-4-12 hex form. Other id shapes
// (numeric, short hashes) are intentionally not matched — adding them
// would risk false-positives that point operators at the wrong agent.
// ---------------------------------------------------------------------------

const UUID_PATTERN = /\b([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\b/i;

function extractSessionIdFromAlert(alert: AlertData): string | null {
  // Try metadata JSON first — structured fields beat regex.
  if (alert.metadata) {
    try {
      const parsed = JSON.parse(alert.metadata);
      if (parsed && typeof parsed === "object") {
        const candidate =
          (parsed as Record<string, unknown>).session_id
          ?? (parsed as Record<string, unknown>).sessionId;
        if (typeof candidate === "string" && UUID_PATTERN.test(candidate)) {
          return candidate;
        }
      }
    } catch {
      // metadata isn't always JSON — fall through to description.
    }
  }
  // Description fallback — session-watcher pattern: "Session: <uuid>".
  if (alert.description) {
    const m = alert.description.match(/Session:\s*([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/i);
    if (m) return m[1];
    // Generic fallback: any UUID anywhere in the description.
    const anyUuid = alert.description.match(UUID_PATTERN);
    if (anyUuid) return anyUuid[1];
  }
  return null;
}

// ---------------------------------------------------------------------------
// Stage metadata
// ---------------------------------------------------------------------------

const STAGE_TITLES: Record<TriageStageId, string> = {
  evidence: "Evidence",
  sourceEvent: "Source Event",
  affectedObject: "Affected Object",
  relatedActivity: "Related Activity",
  fixControl: "Fix / Control",
};

const STAGE_EYEBROW: Record<TriageStageId, string> = {
  evidence: "01",
  sourceEvent: "02",
  affectedObject: "03",
  relatedActivity: "04",
  fixControl: "05",
};

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/**
 * resolveAlertTriageGraph
 *
 * Converts a real AlertData + optional EvidencePayload into a safe TriageGraph.
 * Pure: no I/O, no fetch, no side effects.
 */
export function resolveAlertTriageGraph(input: ResolveAlertTriageInput): TriageGraph {
  const { alert, evidence, now = new Date() } = input;

  // 1. Map issue summary from safe alert metadata only
  const issue: TriageIssueSummary = buildIssueSummary(alert, evidence);

  // 2. Build all artifacts in canonical stage order
  const artifacts: TriageArtifact[] = [
    buildEvidenceArtifact(alert, evidence),
    buildSourceEventArtifact(alert, evidence),
    buildAffectedObjectArtifact(alert, evidence),
    buildRelatedActivityArtifact(alert, evidence, now),
    buildFixControlArtifact(alert, evidence),
  ];

  // 3. Build one stage per canonical stage ID, summarised from its artifacts
  const stages: TriageStage[] = TRIAGE_STAGE_ORDER.map((stageId) =>
    buildStage(stageId, artifacts),
  );

  // 4. Pick the default artifact: first resolved, then first non-restricted,
  //    then the first artifact unconditionally.
  const defaultArtifactId =
    artifacts.find((a) => a.state === "resolved")?.id ??
    artifacts.find((a) => a.state !== "restricted")?.id ??
    artifacts[0]?.id;

  return {
    issue,
    stages,
    artifacts,
    defaultArtifactId,
    generatedAt: now.toISOString(),
    resolverVersion: RESOLVER_VERSION,
  };
}

// ---------------------------------------------------------------------------
// Issue summary builder
// ---------------------------------------------------------------------------

function buildIssueSummary(
  alert: AlertData,
  evidence: EvidencePayload | null | undefined,
): TriageIssueSummary {
  // Derive a safe one-line summary from metadata only — no raw payload
  const summary = alert.description
    ? trimSafe(alert.description, 140)
    : `Alert from ${alert.source} — ${alert.severity} severity, status: ${alert.status ?? "open"}.`;

  // Build safe tags from known metadata fields
  const tags: TriageIssueSummary["tags"] = [];
  tags.push({ label: "source", value: alert.source, safe: true });

  // Rule key from evidence detections (first detection that has one)
  const ruleKey = evidence?.detections?.find((d) => d.rule_key)?.rule_key;
  if (ruleKey) {
    tags.push({ label: "rule_key", value: ruleKey, safe: true });
  }

  // Session ID from evidence (non-raw metadata field)
  if (evidence?.session_id) {
    tags.push({ label: "session", value: evidence.session_id, safe: true });
  }

  // Model from evidence (metadata — not payload content)
  if (evidence?.model) {
    tags.push({ label: "model", value: evidence.model, safe: true });
  }

  // Prompt hash is a hash — safe to surface as a tag (not the content)
  if (evidence?.prompt_hash) {
    tags.push({ label: "prompt_hash", value: evidence.prompt_hash, safe: true });
  }

  // Normalise severity to the union expected by TriageIssueSummary.
  // AlertData.severity is a plain string; cast to the union only if it matches.
  const knownSeverities = ["CRIT", "HIGH", "MED", "WARN", "LOW"] as const;
  type KnownSev = (typeof knownSeverities)[number];
  const severityUpper = alert.severity?.toUpperCase() as string;
  const severity: KnownSev | undefined = (knownSeverities as readonly string[]).includes(
    severityUpper,
  )
    ? (severityUpper as KnownSev)
    : undefined;

  return {
    id: alert.id,
    kind: "alert",
    title: alert.title,
    severity,
    status: alert.status ?? "open",
    source: alert.source,
    summary,
    tags,
    createdAt: alert.created_at,
    updatedAt: alert.updated_at,
  };
}

// ---------------------------------------------------------------------------
// Artifact builders
// ---------------------------------------------------------------------------

/**
 * Evidence artifact (stage: evidence)
 *
 * Backed by the EvidencePayload.audit_event_id field.
 * State rules:
 *   resolved  — audit_event_id present + correlation_method "forward" (exact)
 *   derived   — audit_event_id present + correlation_method "fallback_nearest"
 *   missing   — no audit_event_id on the payload (or no payload at all)
 */
function buildEvidenceArtifact(
  alert: AlertData,
  evidence: EvidencePayload | null | undefined,
): TriageArtifact {
  const auditEventId = evidence?.audit_event_id ?? null;
  const correlationMethod = evidence?.correlation_method ?? null;

  // Determine state — "forward" is exact; "fallback_nearest" is heuristic
  const state = !auditEventId
    ? "missing"
    : correlationMethod === "forward"
      ? "resolved"
      : "derived";

  const shortLabel = auditEventId ? `Evidence · ${auditEventId}` : "Evidence";

  // Safe preview fields — metadata only, no payload content
  const previewFields: TriageArtifact["previewFields"] = [];
  if (auditEventId) {
    previewFields.push({ label: "audit_event_id", value: auditEventId, tone: "default" });
  }
  if (correlationMethod) {
    previewFields.push({
      label: "correlation_method",
      value: correlationMethod,
      tone: correlationMethod === "forward" ? "good" : "warn",
    });
  }
  if (evidence?.verdict) {
    previewFields.push({ label: "verdict", value: evidence.verdict, tone: "warn" });
  }
  if (evidence?.score != null) {
    previewFields.push({ label: "score", value: String(evidence.score), tone: "default" });
  }
  // Detection count — safe aggregate, not raw data
  if (evidence?.detections && evidence.detections.length > 0) {
    previewFields.push({
      label: "detections",
      value: `${evidence.detections.length} detection${evidence.detections.length !== 1 ? "s" : ""}`,
      tone: "muted",
    });
  }

  // Primary action — only when there is an audit_event_id to navigate to
  const primaryAction: TriageArtifact["primaryAction"] = auditEventId
    ? {
        tab: "auditEvidence" as TabId,
        opts: {
          id: auditEventId,
          highlight: auditEventId,
          fromAlert: alert.id,
          focusAlertId: alert.id,
          fromMissionControl: false,
        },
        label: "Open evidence ▸",
      }
    : undefined;

  return {
    id: `${alert.id}-evidence`,
    stageId: "evidence",
    label: shortLabel,
    shortLabel,
    kind: "evidence",
    state,
    confidence: state === "resolved" ? "exact" : state === "derived" ? "medium" : undefined,
    previewTitle: shortLabel,
    previewSummary:
      auditEventId
        ? "Correlated audit event. Raw sample and token data are available in Audit & Evidence under RBAC redaction."
        : missingEvidenceReason(alert),
    previewFields,
    primaryAction,
    reason: state === "missing" ? missingEvidenceReason(alert) : undefined,
    lastResolvedAt: state === "resolved" ? evidence?.audit_created_at : undefined,
    // Spec §10 amendment 2026-05-07: surface the first server-side-redacted
    // match-span snippet from EvidencePayload behind a default-collapsed
    // "Show match span" toggle (rendered in TriageArtifactPreview). The
    // snippet content here is the SAME pre-redacted data EvidenceInline
    // renders on Audit & Evidence — not raw payload. operator requested this
    // for "super-quick decision" triage UX. Only populated when the alert's
    // EvidencePayload has at least one matched-snippet entry.
    evidenceSnippet: pickFirstSnippet(evidence),
  };
}

/**
 * Pick the first matched-snippet entry from an EvidencePayload, if any.
 *
 * EvidencePayload.matched_snippets[] is the server-side-redacted match-span
 * array (Shield writes these AFTER masking PII; the bulk-payload field on
 * the same EvidencePayload remains forbidden in triage code). We surface
 * only the first entry — most alerts have one detection; multi-snippet
 * alerts route the operator to Audit & Evidence for the full list.
 */
function pickFirstSnippet(
  evidence: EvidencePayload | null | undefined,
): TriageArtifact["evidenceSnippet"] {
  if (!evidence) return undefined;
  // matched_snippets are added by the server alongside detections; some
  // alerts may have detections without matched-snippet capture.
  const list = evidence.matched_snippets;
  if (!list || list.length === 0) return undefined;
  const first = list[0];
  // Tolerate empty match strings — render won't display the snippet block
  // when match is falsy, so this is just a safety net.
  if (!first || typeof first.snippet_match !== "string") return undefined;
  return {
    before: first.snippet_before || undefined,
    match: first.snippet_match,
    after: first.snippet_after || undefined,
    ruleKey: first.rule_key || undefined,
  };
}

/**
 * Source Event artifact (stage: sourceEvent)
 *
 * Backed by EvidencePayload.proxy_traffic_id.
 * State: resolved if proxy_traffic_id exists, missing otherwise.
 */
function buildSourceEventArtifact(
  alert: AlertData,
  evidence: EvidencePayload | null | undefined,
): TriageArtifact {
  const proxyTrafficId = evidence?.proxy_traffic_id ?? null;
  const promptHash = evidence?.prompt_hash ?? null;

  const state: TriageArtifact["state"] = proxyTrafficId ? "resolved" : "missing";

  const shortLabel = proxyTrafficId
    ? `Source · ${proxyTrafficId}`
    : `Source · ${alert.source}`;

  // Safe preview fields — IDs and metadata only, never request/response content
  const previewFields: TriageArtifact["previewFields"] = [];
  if (proxyTrafficId) {
    previewFields.push({ label: "proxy_traffic_id", value: proxyTrafficId, tone: "default" });
  }
  if (evidence?.model) {
    previewFields.push({ label: "model", value: evidence.model, tone: "default" });
  }
  if (evidence?.provider) {
    previewFields.push({ label: "provider", value: evidence.provider, tone: "default" });
  }
  if (promptHash) {
    previewFields.push({ label: "prompt_hash", value: promptHash, tone: "default" });
  }
  if (evidence?.direction) {
    previewFields.push({ label: "direction", value: evidence.direction, tone: "default" });
  }
  if (evidence?.session_id) {
    previewFields.push({ label: "session_id", value: evidence.session_id, tone: "default" });
  }

  // Build NavigateOpts for traffic monitor
  // prompt_hash goes into filter.q only when present
  const trafficOpts = proxyTrafficId
    ? {
        highlight: proxyTrafficId,
        ...(promptHash ? { filter: { q: promptHash } } : {}),
        fromMissionControl: false,
      }
    : undefined;

  const primaryAction: TriageArtifact["primaryAction"] = proxyTrafficId
    ? {
        tab: "trafficMonitor" as TabId,
        opts: trafficOpts,
        label: "Open in Traffic ▸",
      }
    : undefined;

  return {
    id: `${alert.id}-source-event`,
    stageId: "sourceEvent",
    label: shortLabel,
    shortLabel,
    kind: "source",
    state,
    confidence: state === "resolved" ? "exact" : undefined,
    previewTitle: proxyTrafficId
      ? `Traffic Monitor · ${proxyTrafficId}`
      : `Source · ${alert.source}`,
    previewSummary: proxyTrafficId
      ? "Proxy-traffic row that generated the alert. Raw request/response content is available in Traffic Monitor under RBAC."
      : missingSourceEventReason(alert),
    previewFields,
    primaryAction,
    reason: state === "missing" ? missingSourceEventReason(alert) : undefined,
  };
}

/**
 * Affected Object artifact (stage: affectedObject)
 *
 * Uses session_id from evidence as the primary object ID. Falls back to
 * alert.id itself as a last resort so the stage is never blank.
 */
function buildAffectedObjectArtifact(
  alert: AlertData,
  evidence: EvidencePayload | null | undefined,
): TriageArtifact {
  // Prefer session_id from evidence (the structured field). Fall back to
  // parsing alert.metadata or alert.description (operator-flagged 2026-05-07:
  // session-watcher writes the session UUID into description as
  // "Session: <uuid>" — without this fallback the stage stayed missing
  // when evidence wasn't fetched / didn't carry session_id).
  const sessionId =
    evidence?.session_id
    ?? extractSessionIdFromAlert(alert)
    ?? null;
  const objectId = sessionId ?? null;
  // Track WHICH source the session_id came from so the preview can be
  // honest about confidence (evidence = exact; description regex = derived).
  const sessionFromEvidence = evidence?.session_id != null;

  const state: TriageArtifact["state"] = objectId
    ? sessionFromEvidence ? "resolved" : "derived"
    : "missing";

  const shortLabel = objectId ? `Object · ${objectId}` : `Object · ${alert.source}`;

  const previewFields: TriageArtifact["previewFields"] = [];
  if (sessionId) {
    previewFields.push({ label: "session_id", value: sessionId, tone: "default" });
    if (!sessionFromEvidence) {
      previewFields.push({
        label: "source",
        value: "alert.description",
        tone: "muted",
      });
    }
  }
  if (evidence?.model) {
    previewFields.push({ label: "model", value: evidence.model, tone: "default" });
  }
  if (evidence?.provider) {
    previewFields.push({ label: "provider", value: evidence.provider, tone: "default" });
  }
  // alert.status is safe metadata
  previewFields.push({ label: "alert_status", value: alert.status ?? "open", tone: "default" });

  const primaryAction: TriageArtifact["primaryAction"] = objectId
    ? {
        tab: "agents" as TabId,
        opts: { id: objectId, highlight: objectId },
        label: "Open agent ▸",
      }
    : undefined;

  return {
    id: `${alert.id}-object`,
    stageId: "affectedObject",
    label: shortLabel,
    shortLabel,
    kind: "object",
    state,
    confidence:
      state === "resolved" ? "exact"
      : state === "derived" ? "medium"
      : undefined,
    previewTitle: objectId
      ? `Agents & Sessions · ${objectId}`
      : `Affected Object · ${alert.source}`,
    previewSummary: objectId
      ? sessionFromEvidence
        ? "Session impacted by this alert. Drill in to inspect agent, model, and recent activity."
        : "Session ID extracted from the alert's description text — not yet correlated to a structured evidence row. Drill in to validate against the live agent state."
      : missingAffectedObjectReason(alert),
    previewFields,
    primaryAction,
    reason: state === "missing" ? missingAffectedObjectReason(alert) : undefined,
  };
}

/**
 * Related Activity artifact (stage: relatedActivity)
 *
 * Always state "derived" — this is a pre-built query, not a backing row.
 * Uses rule_key from the first detection with one, then alert source as fallback.
 */
function buildRelatedActivityArtifact(
  alert: AlertData,
  evidence: EvidencePayload | null | undefined,
  now: Date,
): TriageArtifact {
  // Rule key from evidence detections — first detection that has one
  const ruleKey = evidence?.detections?.find((d) => d.rule_key)?.rule_key ?? null;

  const shortLabel = ruleKey ? "Related · same-rule-24h" : "Related · same-source-24h";

  // Time window for the pre-built query
  const timeFilter = makeLastHoursFilter(24, now);

  // Build opts: min/max come from makeLastHoursFilter, q from rule_key if present
  const opts: NonNullable<TriageArtifact["primaryAction"]>["opts"] = {
    filter: {
      ...(ruleKey ? { q: ruleKey } : {}),
      source: [alert.source],
      min: timeFilter.min,
      max: timeFilter.max,
    },
  };

  const previewFields: TriageArtifact["previewFields"] = [];
  if (ruleKey) {
    previewFields.push({ label: "rule_key", value: ruleKey, tone: "default" });
  }
  previewFields.push({ label: "source", value: alert.source, tone: "default" });
  previewFields.push({ label: "window", value: "last 24h", tone: "default" });
  previewFields.push({ label: "confidence", value: "derived (query)", tone: "muted" });

  return {
    id: `${alert.id}-related`,
    stageId: "relatedActivity",
    label: shortLabel,
    shortLabel,
    kind: "related",
    state: "derived",
    confidence: "derived",
    previewTitle: ruleKey
      ? `Alerts · same rule · last 24h`
      : `Alerts · same source · last 24h`,
    previewSummary: ruleKey
      ? `Other alerts matching rule ${ruleKey} in the last 24 hours. Use this to gauge pattern prevalence and blast radius.`
      : `Other alerts from ${alert.source} in the last 24 hours.`,
    previewFields,
    primaryAction: {
      tab: "alertsIncidents" as TabId,
      opts,
      label: "Open related ▸",
    },
  };
}

/**
 * Fix / Control artifact (stage: fixControl)
 *
 * Points to the Policies & Rules configuration surface when a rule_key is known.
 * Falls back to a generic configuration target based on alert.source.
 * State: derived when a sensible target exists, missing when there is no
 * actionable control surface to point to.
 */
function buildFixControlArtifact(
  alert: AlertData,
  evidence: EvidencePayload | null | undefined,
): TriageArtifact {
  const ruleKey = evidence?.detections?.find((d) => d.rule_key)?.rule_key ?? null;

  // Determine target and state
  const hasRuleKey = ruleKey !== null;
  const state: TriageArtifact["state"] = "derived";

  const shortLabel = hasRuleKey
    ? `Fix · Policies & Rules`
    : `Fix · ${alert.source}`;

  const previewFields: TriageArtifact["previewFields"] = [];
  if (hasRuleKey) {
    previewFields.push({
      label: "target",
      value: "Configuration → Policies & Rules",
      tone: "default",
    });
    previewFields.push({ label: "control", value: ruleKey, tone: "default" });
    previewFields.push({
      label: "suggested_action",
      value: "Tune detection threshold or add a policy exception",
      tone: "default",
    });
  } else {
    previewFields.push({ label: "source", value: alert.source, tone: "default" });
    previewFields.push({ label: "target", value: "Configuration", tone: "muted" });
  }
  previewFields.push({ label: "permission", value: "policies:write", tone: "muted" });

  const primaryAction: TriageArtifact["primaryAction"] = {
    tab: "configuration" as TabId,
    opts: hasRuleKey
      ? { focus: "policiesAndRules", filter: { q: ruleKey }, fromMissionControl: false }
      : { focus: "policiesAndRules", fromMissionControl: false },
    label: "Open in Policies & Rules ▸",
  };

  return {
    id: `${alert.id}-fix-control`,
    stageId: "fixControl",
    label: shortLabel,
    shortLabel,
    kind: "fix",
    state,
    confidence: "derived",
    previewTitle: hasRuleKey
      ? "Configuration · Policies & Rules"
      : `Configuration · ${alert.source}`,
    previewSummary: hasRuleKey
      ? `Suppress similar matches, tune the rule, or escalate. Policies & Rules is the canonical control point for ${ruleKey}.`
      : `Configuration surface for ${alert.source}. Use Policies & Rules to adjust detection settings.`,
    previewFields,
    primaryAction,
    permission: "policies:write",
  };
}

// ---------------------------------------------------------------------------
// Stage builder
// ---------------------------------------------------------------------------

function buildStage(stageId: TriageStageId, artifacts: TriageArtifact[]): TriageStage {
  const stageArtifacts = artifacts.filter((a) => a.stageId === stageId);
  // Lead = first resolved artifact, else the first artifact in the stage
  const lead =
    stageArtifacts.find((a) => a.state === "resolved") ?? stageArtifacts[0];

  return {
    id: stageId,
    title: STAGE_TITLES[stageId],
    eyebrow: STAGE_EYEBROW[stageId],
    state: lead?.state ?? "missing",
    summary: lead ? deriveStageSummary(lead) : "Not yet resolved.",
    artifactIds: stageArtifacts.map((a) => a.id),
  };
}

/**
 * deriveStageSummary
 *
 * Pulls a one-line stage summary from an artifact. Uses previewSummary (already
 * safe) trimmed to 160 chars. Falls back to the reason string if present.
 */
function deriveStageSummary(artifact: TriageArtifact): string {
  if (artifact.previewSummary) {
    return trimSafe(artifact.previewSummary, 160);
  }
  if (artifact.reason) {
    return trimSafe(artifact.reason, 160);
  }
  return artifact.label;
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

/**
 * trimSafe — truncate a string to maxLen chars without cutting mid-word,
 * appending "…" when truncation occurs. Safe for operator-grade UI labels.
 */
function trimSafe(str: string, maxLen: number): string {
  if (str.length <= maxLen) return str;
  return str.slice(0, maxLen - 1).replace(/\s+\S*$/, "") + "…";
}
